- name: Install Mongodb component
  hosts: mongodb
  become: yes
  tasks:
  - name: cpoy mongo repo to yum.repos.d
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name: Install MongoDB
    ansible.builtin.yum:
      name: mongodb-org
      state: installed